version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/product
      API_SECURITY_TOKEN_SECRET: my-secret-key